import random
quotes = [
    f"""The only limit to our realization of tomorrow is our doubts of today.""",
    f"""The future belongs to those who believe in the beauty of their dreams.""",
    f"""Do not wait to strike till the iron is hot; but make it hot by striking.""",
    f"""The best way to predict the future is to invent it.""",
    f"""Life is 10% what happens to us and 90% how we react to it.""",
    f"""To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.""",
    f"""The only way to do great work is to love what you do.""",
    f"""If you can dream it, you can achieve it.""",
    f"""You miss 100% of the shots you don't take.""",
    f"""Change your thoughts and you change your world.""",
    f"""Success is not final, failure is not fatal: it is the courage to continue that counts.""",
    f"""Happiness is not something ready made. It comes from your own actions.""",
    f"""Believe you can and you're halfway there.""",
    f"""Fall seven times, stand up eight.""",
    f"""What you get by achieving your goals is not as important as what you become by achieving your goals.""",
    f"""The only thing we have to fear is fear itself.""",
    f"""The best revenge is massive success.""",
    f"""The purpose of our lives is to be happy.""",
    f"""Act as if what you do makes a difference. It does.""",
    f"""You are never too old to set another goal or to dream a new dream.""",
    f"""Life is what happens when you're busy making other plans.""",
    f"""Do not let making a living prevent you from making a life.""",
    f"""You must be the change you wish to see in the world.""",
    f"""Tough times never last but tough people do.""",
    f"""In the end, we will remember not the words of our enemies, but the silence of our friends.""",
    f"""It is during our darkest moments that we must focus to see the light.""",
    f"""Our greatest glory is not in never falling, but in rising every time we fall.""",
    f"""Do what you can, with what you have, where you are.""",
    f"""If you want to lift yourself up, lift up someone else.""",
    f"""Success usually comes to those who are too busy to be looking for it.""",
    f"""Keep your face always toward the sunshine—and shadows will fall behind you.""",
    f"""The only impossible journey is the one you never begin.""",
    f"""Life is really simple, but we insist on making it complicated.""",
    f"""It's not whether you get knocked down, it's whether you get up.""",
    f"""Your time is limited, don't waste it living someone else's life.""",
    f"""Do not follow where the path may lead. Go instead where there is no path and leave a trail.""",
    f"""Life isn't about finding yourself. Life is about creating yourself.""",
    f"""The only way to achieve the impossible is to believe it is possible.""",
    f"""Your life does not get better by chance, it gets better by change.""",
    f"""The greatest glory in living lies not in never falling, but in rising every time we fall.""",
    f"""Do not go where the path may lead, go instead where there is no path and leave a trail.""",
    f"""Life is either a daring adventure or nothing at all.""",
    f"""The greatest wealth is to live content with little.""",
    f"""Life is what we make it, always has been, always will be.""",
    f"""Life is short, and it is up to you to make it sweet.""",
    f"""If you tell the truth, you don't have to remember anything.""",
    f"""The most wasted of days is one without laughter.""",
    f"""Life itself is the most wonderful fairy tale.""",
    f"""The journey of a thousand miles begins with one step.""",
    f"""Dream big and dare to fail.""",
    f"""It always seems impossible until it’s done.""",
    f"""The best way out is always through.""",
    f"""What we think, we become.""",
    f"""What lies behind us and what lies before us are tiny matters compared to what lies within us.""",
    f"""Life shrinks or expands in proportion to one's courage.""",
    f"""Keep your eyes on the stars and your feet on the ground.""",
    f"""The only real mistake is the one from which we learn nothing.""",
    f"""What you do today can improve all your tomorrows.""",
    f"""It is never too late to be what you might have been.""",
    f"""Quality is not an act, it is a habit.""",
    f"""Your present circumstances don’t determine where you can go; they merely determine where you start.""",
    f"""Limit your ‘always’ and your ‘nevers’.""",
    f"""He who has a why to live can bear almost any how.""",
    f"""Turn your wounds into wisdom.""",
    f"""Don’t wait. The time will never be just right.""",
    f"""You must do the things you think you cannot do.""",
    f"""We must embrace pain and burn it as fuel for our journey.""",
    f"""If you have everything under control, you’re not moving fast enough.""",
    f"""The harder the conflict, the greater the triumph.""",
    f"""A person who never made a mistake never tried anything new.""",
    f"""Go confidently in the direction of your dreams! Live the life you’ve imagined.""",
    f"""You are enough just as you are.""",
    f"""I have not failed. I've just found 10,000 ways that won't work.""",
    f"""Out of difficulties grow miracles.""",
    f"""The best preparation for tomorrow is doing your best today.""",
    f"""Once you choose hope, anything’s possible.""",
    f"""Hardships often prepare ordinary people for an extraordinary destiny.""",
    f"""We know what we are, but know not what we may be.""",
    f"""Spread love everywhere you go.""",
    f"""If opportunity doesn’t knock, build a door.""",
    f"""Perseverance is not a long race; it is many short races one after the other.""",
    f"""When you have a dream, you've got to grab it and never let go.""",
    f"""Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.""",
    f"""I attribute my success to this: I never gave or took any excuse.""",
    f"""The greatest discovery of all time is that a person can change their future by merely changing their attitude.""",
    f"""The more you praise and celebrate your life, the more there is in life to celebrate.""",
    f"""If you want to be happy, be.""",
    f"""The best way to cheer yourself up is to try to cheer somebody else up.""",
    f"""Happiness often sneaks in through a door you didn’t know you left open.""",
    f"""Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.""",
    f"""Believe you can and you’re halfway there.""",
    f"""In the middle of every difficulty lies opportunity.""",
    f"""Happiness is not by chance, but by choice.""",
    f"""The more you praise and celebrate your life, the more there is in life to celebrate.""",
    f"""Let us make our future now, and let us make our dreams tomorrow’s reality.""",
    f"""You don’t need to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.""",
    f"""Change the world by being yourself.""",
    f"""If you want to lift yourself up, lift up someone else.""",
    f"""What we achieve inwardly will change outer reality."""
]